{% set name = "xenv" %}
{% set version = "0.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/xenv-{{ version }}.tar.gz
  sha256: 0e83a4bc157641c4d905a1ef9d14b1c0cde7d5792615d9ba40ccb5778a84bcd6

build:
  entry_points:
    - xenv = xenv:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools >=61.2
    - setuptools-scm
    - pip
  run:
    - python >=3.7

test:
  imports:
    - xenv
  commands:
    - pip check
    - xenv --help
  requires:
    - pip

about:
  home: https://gitlab.cern.ch/lhcb-core/xenv
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: Run commands in modified environment
  doc_url: https://gitlab.cern.ch/lhcb-core/xenv
  dev_url: https://gitlab.cern.ch/lhcb-core/xenv

extra:
  recipe-maintainers:
    - chrisburr
