{% set name = "xenv" %}
{% set version = "1.0.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: cea9547295f0bd07c87e68353bb9eb1c2f2d1c09a840e3196c19cbc807ee4558

build:
  number: 1
  noarch: python
  entry_points:
    - xenv=xenv:main
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools_scm
    - setuptools
    - nose
  run:
    - python >={{ python_min }}
    - setuptools

test:
  requires:
    - python {{ python_min }}
  imports:
    - xenv
  commands:
    - xenv --help

about:
  home: https://gitlab.cern.ch/lhcb-core/xenv
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Run commands in modified environment
  doc_url: https://gitlab.cern.ch/lhcb-core/xenv
  dev_url: https://gitlab.cern.ch/lhcb-core/xenv

extra:
  recipe-maintainers:
    - chrisburr
