provider: {linux_aarch64: default, linux_ppc64le: default}
build_platform:
  linux_aarch64: linux_64
  linux_ppc64le: linux_64
  osx_arm64: osx_64
conda_forge_output_validation: true
bot:
  automerge: true
  abi_migration_branches:
  - master
  - 0.0.4
conda_build:
  pkg_format: '2'
